<?php

namespace SBC\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $query = $this->createQueryBuilder('u')
            ->orderBy('u.id', 'DESC')
            ->getQuery();
        return $query->getResult();
    }


    public function find($id, $lockMode = null, $lockVersion = null)
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.id = ?1')
            ->setParameters(array(1 => $id))
            ->getQuery();
        return $query->getOneOrNullResult();
    }

    public function findOneBy(array $criteria, array $orderBy = null)
    {
        $query = $this->createQueryBuilder('u');
        $i = 0;
        foreach ($criteria as $key => $value) {
            if ($i == 0)
                $query->where('u.' . $key . ' = :value');
            else
                $query->andWhere('u.' . $key . ' = :value');
            $query->setParameter('value', $value);
            $i++;
        }
        return $query->getQuery()->getOneOrNullResult();
    }
}
