# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        SBC\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:   ^/
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                # redirection après authentification
                always_use_default_target_path: false
                default_target_path:            /back-office/utilisateurs
                target_path_parameter:          _target_path
                use_referer:                    false
                post_only:      true
            logout:
                path:       fos_user_security_logout
                target:     /back-office/login

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
