<?php

namespace SBC\GrifoflexTunisieBundle\Repository;

/**
 * ApplicationMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationMailRepository extends \Doctrine\ORM\EntityRepository
{
}
