<?php

namespace SBC\GrifoflexTunisieBundle\Repository;

/**
 * ContactMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMailRepository extends \Doctrine\ORM\EntityRepository
{
}
