<?php

namespace SBC\GrifoflexTunisieBundle\Repository;

/**
 * EventPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPictureRepository extends \Doctrine\ORM\EntityRepository
{
}
