<?php

namespace SBC\GrifoflexTunisieBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param mixed $id
     * @param null $lockMode
     * @param null $lockVersion
     * @return mixed
     */
    public function find($id, $lockMode = null, $lockVersion = null)
    {
        $query = $this->createQueryBuilder('product')
            ->leftJoin('product.pictures', 'pictures')
            ->addSelect('pictures')
            ->leftJoin('product.category', 'category')
            ->addSelect('category')
            ->where('product.id = ?1')
            ->getQuery();
        $query->setParameters(array(1 => $id));

        return $query->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function findAll()
    {
        $query = $this->createQueryBuilder('product')

            ->leftJoin('product.category', 'category')
            ->addSelect('category')
            ->getQuery();
        return $query->getResult();
    }
}
