<?php

namespace SBC\GrifoflexTunisieBundle\Repository;

/**
 * ProductPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPictureRepository extends \Doctrine\ORM\EntityRepository
{
}
