<?php

namespace SBC\GrifoflexTunisieBundle\Repository;

/**
 * QuotationProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationProductRepository extends \Doctrine\ORM\EntityRepository
{
}
