<?php

namespace SBC\GrifoflexTunisieBundle\Repository;

/**
 * QutationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QutationRepository extends \Doctrine\ORM\EntityRepository
{
}
